# Generated by Django 6.0.4 on 2026-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_image_url_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='locker_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
