# Generated by Django 6.0.4 on 2026-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_locker_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltransaction',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
