# Generated by Django 6.0.4 on 2026-05-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rentaltransaction_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
